### ISSUE TITLE
Diagnostics for necessary permissions

### ISSUE THREAD

**Issue by minorczyka** [googleinterns/recomator#55]
It would be great to allow users to run diagnostics checking if our app has all necessary permissions to list and apply recommendations in all their projects and if all APIs are enabled.

Ideally we would display table with the list of all their projects with checkboxes for each necessary permission.

**Comment by ViktoriiaKovalova** [comment]
I was using services.get from Service Usage API (to test APIs enabled) and projects.testIamPermissions for Cloud Resource Manager API to test permissions.
There's one problem with that, if the Service Usage API was disabled for the project, services.get will itself result in 403 error. Also I need serviceusage.services.get permission for this method. So we should handle it somehow. Right now i just return that service usage api is disabled if it returns 403.
projects.testIamPermissions doesn't need any permissions so there won't be any problems with that.
